INSERT INTO USER VALUES ('sford', 'sam_is_great', 'Sam', 'Ford', 'sford3@gatech.edu', '555-555-5555');
INSERT INTO USER VALUES ('cclegg', 'chris_is_great', 'Chris', 'Clegg', 'cclegg3@gatech.edu', '555-555-5555');
INSERT INTO USER VALUES ('hkim', 'hokeun_is_great', 'Ho Keun', 'Kim', 'hkim3@gatech.edu', '555-555-5555');
INSERT INTO USER VALUES ('jparkhurst', 'joanna_is_great', 'Joanna', 'Parkhurst', 'jparkhurst3@gatech.edu', '555-555-5555');
INSERT INTO USER VALUES ('zhancock', 'zack_is_great', 'Zack', 'Hancock', 'zhancock3@gatech.edu', '555-555-5555');

INSERT INTO SERVICE (Name) VALUES ('Database');
INSERT INTO SERVICE (Name) VALUES ('UI');
INSERT INTO SERVICE (Name) VALUES ('Server');

INSERT INTO TEAM (Name) VALUES ('Database Team');
INSERT INTO TEAM (Name) VALUES ('UI Team');
INSERT INTO TEAM (Name) VALUES ('Server Team');

INSERT INTO SCHEDULE VALUES (1, 'Default');
INSERT INTO SCHEDULE VALUES (2, 'Default');
INSERT INTO SCHEDULE VALUES (3, 'Default');

INSERT INTO ESCALATION_LEVEL VALUES (1,1,0);
INSERT INTO ESCALATION_LEVEL VALUES (1,2,10);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('sford', 1, 1);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('cclegg', 1, 1);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('hkim', 1, 2);
INSERT INTO SCHEDULE_IN_ESCALATION_LEVEL VALUES (1,'Default',1,2);

INSERT INTO ESCALATION_LEVEL VALUES (2,1,0);
INSERT INTO ESCALATION_LEVEL VALUES (2,2,20);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('jparkhurst', 2, 1);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('zhancock', 2, 2);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('sford', 2, 2);
INSERT INTO SCHEDULE_IN_ESCALATION_LEVEL VALUES (2,'Default',2,1);

INSERT INTO ESCALATION_LEVEL VALUES (3,1,0);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('jparkhurst', 3, 1);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('cclegg', 3, 1);
INSERT INTO USER_IN_ESCALATION_LEVEL VALUES ('hkim', 3, 1);
INSERT INTO SCHEDULE_IN_ESCALATION_LEVEL VALUES (3,'Default',3,1);


